### ISSUE TITLE
cannot import name 'normalization

### ISSUE THREAD

**Issue by ffdown** [WSJUSA/Comfyui-StableSR#2]
Traceback (most recent call last):
  File "E:\AI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI\custom_nodes\Comfyui-StableSR\__init__.py", line 15, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI\ComfyUI\custom_nodes\Comfyui-StableSR\nodes.py", line 15, in <module>
    import stablesr
  File "E:\AI\ComfyUI\custom_nodes\Comfyui-StableSR\modules\stablesr.py", line 56, in <module>
    from spade import SPADELayers
  File "E:\AI\ComfyUI\custom_nodes\Comfyui-StableSR\modules\spade.py", line 10, in <module>
    from ldm.modules.diffusionmodules.util import normalization, checkpoint
ImportError: cannot import name 'normalization' from 'ldm.modules.diffusionmodules.util' (E:\AI\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py)

Cannot import E:\AI\ComfyUI\custom_nodes\Comfyui-StableSR module for custom nodes: cannot import name 'normalization' from 'ldm.modules.diffusionmodules.util' (E:\AI\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py)

**Comment by thekitchenscientist** [comment]
You can get the missing functions from https://[huggingface.co/spaces/multimodalart/latentdiffusion/raw/main/latent-diffusion/ldm/modules/diffusionmodules/util.py](https://huggingface.co/spaces/multimodalart/latentdiffusion/raw/main/latent-diffusion/ldm/modules/diffusionmodules/util.py) but then you will get the matmul error instead

**Comment by botnang** [comment]
same issues. 

![image](https://github.com/WSJUSA/Comfyui-StableSR/assets/32015065/9a160ace-0cb2-4335-aba8-57c12ae6d6d9)

**Comment by thekitchenscientist** [comment]
I ended up switching to the code base at https://github.com/cubiq/ComfyUI_InstantID this worked without any issues
